### ISSUE TITLE
i need help for run toshiba tmp96c141

### ISSUE THREAD

**Issue by mohammad0663** [KubaO/asl#4]
hi . 
i need help for run toshiba tmp96c141.
I need to program tmp96c141 processor with keil compiler or arduino.
I didn't read your source and I don't know assembler.
I really need your help.

**Comment by 0cjs** [comment]
This is not the place to ask how to learn to program in assembler. If this is related to a course, I suggest you talk to your instructor or TA. Otherwise you should search for a discussion forum on the web that would welcome a question like this.

**Comment by mohammad0663** [comment]
You didn't even understand what I said
