### ISSUE TITLE
Sync out of date

### ISSUE THREAD

**Issue by alechenninger** [KubaO/asl#5]
It looks like this repository stopped syncing with the [latest source](http://john.ccac.rwth-aachen.de:8000/as/download.html), which appears to be last updated December 1 as of writing.

**Comment by 0cjs** [comment]
Sorry about that! I've just updated it to the latest release as of this post; `asl-current-142-bld256`. Let me know if things are ok now.

**Comment by alechenninger** [comment]
Thanks!
